# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroTour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('authority', models.IntegerField(default=0)),
            ],
        ),
    ]
