# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroTour', '0003_auto_20170327_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='abc'),
        ),
    ]
