# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroTour', '0004_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(default='abc', primary_key=True),
        ),
    ]
