# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroTour', '0005_auto_20170327_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
